global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  # SLOW producer — JMX exporter on port 9091
  - job_name: 'kafka-producer-slow'
    static_configs:
      - targets: ['host.docker.internal:9091']
        labels:
          profile: 'slow'

  # FAST producer — JMX exporter on port 9092
  - job_name: 'kafka-producer-fast'
    static_configs:
      - targets: ['host.docker.internal:9092']
        labels:
          profile: 'fast'